name: Social Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "02_cicd/social-frontend/**"
      - ".github/workflows/social-frontend.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Image
        run: |
          sudo docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/social-frontend:latest \
            ./02_cicd/social-frontend

      - name: Push Image
        run: |
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/social-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-frontend:latest

            sudo docker stop social-frontend || true
            sudo docker rm social-frontend || true

            sudo docker run -d \
              --name social-frontend \
              --restart unless-stopped \
              -p 80:3000 \
              ${{ secrets.DOCKER_USERNAME }}/social-frontend:latest